version: 2

run:
  timeout: 5m
  modules-download-mode: readonly

issues:
  exclude-use-default: false
  max-same-issues: 1
  max-issues-per-linter: 0
  exclude:
    - "error return value not checked.*(Close|Write|Read)"
    - "should have comment or be unexported"
    - "exported:.*should have comment or be unexported"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gocyclo
    - gosec
    - ineffassign
    - dupl
    - gocritic
    - unparam
    - misspell
    - dogsled
  disable:
    - lll
    - gochecknoglobals
    - revive
    - depguard

linters-settings:
  errcheck:
    exclude:
      - 'fmt\.F.*'
      - 'os\.(Chdir|Getwd)'
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  gosec:
    exclude:
      - G104
      - G101
  revive:
    config: "./revive.toml"
  misspell:
    locale: US

skip-dirs:
  - vendor
  - third_party

cache:
  enabled: true
  dir: ".cache/golangci"