ignoreGeneratedHeader = true
severity = "warning"   
confidence = 0.8        

[[rule]]
name = "error-strings"

[[rule]]
name = "error-check"

[rule.params]
ignoreRegex = 'fmt\.(F|Print)f?'

[[rule]]
name = "naked-return"

[[rule]]
name = "unused-result"

[[rule]]
name = "import-shadow"

[[rule]]
name = "package-comments"

[[rule]]
name = "cyclomatic"
[rule.params]
max = 15

[[rule]]
name = "indent-error-flow"

[[rule]]
name = "blank-imports"
[rule.params]
exclude = ["_"]

[[rule]]
name = "var-naming"
[rule.params]
regexp = "^[a-z][A-Za-z0-9]*$"

[[rule]]
name = "shadow"

[[rule]]
name = "structtag"

[[rule]]
name = "nesting"
[rule.params]
max = 3

[[rule]]
name = "error-format"

